eStore/Controllers/AuthController.cs
using BusinessObject;
using eStore.Models;
using eStore.Models.Dto;
using eStore.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System;
using System.Threading.Tasks;
using System.Linq;

namespace eStore.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;

        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        public IActionResult Index()
        {
            return RedirectToAction("Login");
        }

        [HttpGet]
        public async Task<IActionResult> Login()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString(SD.SessionEmail)))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDTO obj)
        {
            if (ModelState.IsValid)
            {
                var res = await _authService.LoginAsync<APIResponse>(obj);

                if (res != null && res.IsSuccess)
                {
                    LoginResponseDTO model = JsonConvert.DeserializeObject<LoginResponseDTO>(Convert.ToString(res.Result));

                    HttpContext.Session.SetString(SD.SessionEmail, model.Email);
                    HttpContext.Session.SetString(SD.SessionRole, model.Role);
                    if (model.Member.MemberId > 0)
                    {
                        HttpContext.Session.SetInt32(SD.SessionID, model.Member.MemberId);
                    }
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("CustomError", res.ErrorMessages.SingleOrDefault());
                }
            }
            return View(obj);
        }

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString(SD.SessionEmail)))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterationRequestDTO obj)
        {
            if (ModelState.IsValid)
            {
                APIResponse result = await _authService.RegisterAsync<APIResponse>(obj);
                if (result != null && result.IsSuccess)
                {
                    return RedirectToAction("Login");
                }
                ModelState.AddModelError("CustomError", result.ErrorMessages.SingleOrDefault());
            }
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove(SD.SessionEmail);
            HttpContext.Session.Remove(SD.SessionID);
            HttpContext.Session.Remove(SD.SessionRole);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

eStore/Controllers/OrderController.cs
using eStore.Models.Dto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Collections.Generic;
using System;
using eStore.Services;
using eStore.Models;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;

namespace eStore.Controllers
{
    public class OrderController : Controller
    {
        private readonly IProductService _product;
        private readonly IOrderService _order;
        private readonly IOrderDetailService _orderDetail;
        private readonly IMapper _mapper;

        public OrderController(IProductService product, IOrderService order, IOrderDetailService orderDetail, IMapper mapper)
        {
            _product = product;
            _order = order;
            _orderDetail = orderDetail;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Details(int id)
        {
            if (HttpContext.Session.GetInt32(SD.SessionID) > 0)
            {
                ProductDTO model = null;

                var productRes = await _product.GetAsync<APIResponse>(id);
                if (productRes != null && productRes.IsSuccess)
                {
                    model = JsonConvert.DeserializeObject<ProductDTO>(Convert.ToString(productRes.Result));

                    OrderDetailDTO orderDetail = _mapper.Map<OrderDetailDTO>(model);

                    if (orderDetail != null)
                    {
                        orderDetail.TempPrice = orderDetail.UnitPrice * orderDetail.Quantity * (1 - orderDetail.Discount / 100);
                        return View(orderDetail);
                    }
                }
            }
            else
            {
                return RedirectToAction("", "Home");
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult OrderConfirmation()
        {
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OrderConfirmation(OrderDetailDTO orderDetail)
        {
            if (HttpContext.Session.GetInt32(SD.SessionID) > 0)
            {
                if (ModelState.IsValid)
                {
                    var orderCreate = _mapper.Map<OrderCreateDTO>(orderDetail);
                    orderCreate.MemberId = (int)HttpContext.Session.GetInt32(SD.SessionID);

                    var orderRes = await _order.CreateAsync<APIResponse>(orderCreate);

                    if (orderRes != null && orderRes.IsSuccess)
                    {
                        OrderResponseDTO orderResponse = JsonConvert.DeserializeObject<OrderResponseDTO>(Convert.ToString(orderRes.Result));

                        return View(orderResponse);
                    }
                    TempData["available"] = "Not available";
                }
            }
            return RedirectToAction("Details", new { id = orderDetail.ProductId });
        }

        [HttpGet]
        public async Task<IActionResult> History()
        {
            if (HttpContext.Session.GetInt32(SD.SessionID) > 0)
            {
                List<ProductSalesDTO> listOrders = new List<ProductSalesDTO>();

                var response = await _orderDetail.GetAsync<APIResponse>((int)HttpContext.Session.GetInt32(SD.SessionID));

                if (response != null && response.IsSuccess)
                {
                    listOrders = JsonConvert.DeserializeObject<List<ProductSalesDTO>>(Convert.ToString(response.Result));
                }

                return View(listOrders);
            }
            return RedirectToAction("", "Home");

        }
    }
}

eStore/Controllers/ProfileController.cs
using eStore.Models.Dto;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System;
using AutoMapper;
using eStore.Services;
using eStore.Models;

namespace eStore.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IMemberService _service;
        public ProfileController(IMemberService service, IMapper mapper)
        {
            _service = service;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString(SD.SessionEmail)))
            {
                if (HttpContext.Session.GetInt32(SD.SessionID).HasValue)
                {
                    var response = await _service.GetAsync<APIResponse>((int)HttpContext.Session.GetInt32(SD.SessionID));
                    if (response != null && response.IsSuccess)
                    {
                        MemberEditDTO mem = JsonConvert.DeserializeObject<MemberEditDTO>(Convert.ToString(response.Result));

                        return View(mem);
                    }
                }
                else
                {
                    return View();
                }             
            }
            return Redirect("/");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(MemberEditDTO model)
        {
            if (ModelState.IsValid)
            {
                var response = await _service.UpdateAsync<APIResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Information has updated";
                    return RedirectToAction(nameof(Index));
                }
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

eStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (Context.Session.GetString(SD.SessionRole) != "Admin" && !string.IsNullOrEmpty(Context.Session.GetString(SD.SessionEmail)))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="History">Ordered</a>
                            </li>
                        }
                        @if (Context.Session.GetString(SD.SessionRole) == "Admin")
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                                    Manage
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item dropdown-item">
                                        <a class="nav-link text-dark" asp-area="Manage" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item dropdown-item">
                                        <a class="nav-link text-dark" asp-area="Manage" asp-controller="Member" asp-action="Index">Member</a>
                                    </li>
                                    <li class="nav-item dropdown-item">
                                        <a class="nav-link text-dark" asp-area="Manage" asp-controller="Sales" asp-action="Index">Sales</a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (!string.IsNullOrEmpty(Context.Session.GetString(SD.SessionEmail)))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="profile" asp-area="" asp-controller="Profile" asp-action="Index">Hello @Context.Session.GetString(SD.SessionEmail)!</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="logout" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="login" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="register" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - eStore
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>